### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by AZKZero** [naveedhassan913/YouTubeExtractor#51]
When I try to extract url of videos I get this error:
W/System.err: java.io.FileNotFoundException: https://www.youtube.com/watch?v=HGSR3FDVkkQ&has_verified=1&bpctr=9999999999
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
W/System.err:     at ---.----.----.youtube.utils.HTTPUtility.downloadPageSource(HTTPUtility.java:47)
W/System.err:     at ---.----.----.youtube.YoutubeStreamExtractor.doInBackground(YoutubeStreamExtractor.java:105)
W/System.err:     at ---.----.----.youtube.YoutubeStreamExtractor.doInBackground(YoutubeStreamExtractor.java:27)
W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)

video Id: HGSR3FDVkkQ
HTTP response:
Too Many Requests
{null=[HTTP/1.1 429 Too Many Requests], Alt-Svc=[h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"], Cache-Control=[no-cache, no-store, max-age=0, must-revalidate], Content-Type=[text/html; charset=utf-8], Date=[Tue, 27 Jul 2021 16:42:09 GMT], Expires=[Mon, 01 Jan 1990 00:00:00 GMT], Pragma=[no-cache], Server=[ESF], Strict-Transport-Security=[max-age=31536000], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1627404127918], X-Android-Response-Source=[NETWORK 429], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1627404127769], X-Content-Type-Options=[nosniff], X-Frame-Options=[SAMEORIGIN], X-XSS-Protection=[0]}

**Comment by AZKZero** [comment]
@nhCoder
